config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about' ,to: 'welcome#about'
  get 'test', to: 'welcome#test'
  resources :bookings do
    member do
      get :delete
    end
  end

  get 'signup', to: 'users#joke'

  get 'okyouaremyfriend', to: 'users#new'

  resources :users , except:[:new] do
    member do
      get :delete
    end
  end

  get 'get_in', to:'sessions#new'
  post 'get_in', to:'sessions#create'
  get 'bye', to:'sessions#delete'

  resources :categories, except:[:delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :user, optional: true
  has_many :booking_categories
  has_many :categories, through: :booking_categories
  has_one_attached :image

validates :Movie , presence:true, length: {minimum: 3 , maximum: 30},uniqueness: true
validates :Description , presence:true, length: {minimum: 3, maximum: 3000 },uniqueness: true
validates :Rating , presence:true, length: {minimum: 0, maximum: 100 }
validates :user_id, presence: true



end

app/models/booking_category.rb
class BookingCategory < ApplicationRecord

  belongs_to :booking
  belongs_to :category

end

app/models/bookings.rb
class Bookings < ApplicationRecord

  belongs_to :user

validates :Movie , presence:true, length: {minimum: 3 , maximum: 30},uniqueness: true
validates :Description , presence:true, length: {minimum: 3, maximum: 3000 },uniqueness: true
validates :Rating , presence:true, length: {minimum: 0, maximum: 100 }
validates :user_id, presence: true



end

app/models/category.rb
class Category < ApplicationRecord
  validates :name,
            presence: true,
            length: {minimum: 3, maximum: 30}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings, dependent: :destroy

  before_save {self.email =email.downcase}

validates :username, presence: true, length: {minimum: 3, maximum: 25},
          uniqueness: {case_sensitive: false}

VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            length: {maximum: 105},
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  helper_method :current_user,:logged_in?,:timenow,:give_time

  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger]="Hey You Gotta Login First"
      redirect_to root_path
    end
  end

  def timenow

    a=Time.now.to_s
    arr=[]
    arr=a.split(' ')
    arr[1]=arr[1].to_s
    array=arr[1].split(':')
    return("#{array[0]}:#{array[1]}:#{array[2]}")
  end

  def give_time
    @time = Time.now.utc.to_s.split(" ").second
    render :partial => 'layouts/time_portion'
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only:[:destroy,:update,:show,:edit,:delete]
  before_action :require_user, except:[:index,:show]
  before_action :require_same_user, only:[:edit,:update,:delete]

  #index page
  def index
    @bookings= Booking.paginate(page: params[:page], per_page:5)
  end

  #New user Object
  def new
    @bookings =Booking.new
  end

  #delete Option
  def delete


    @bookings.destroy
    flash[:danger]="Movie Deleted from List"
    redirect_to bookings_path(@bookings)
  end

  #Create Action
  def create

  @bookings = Booking.new(bookings_params)
  @bookings.user = current_user

  if @bookings.save
   flash[:success] = "Data was Added to Database"
   redirect_to booking_path(@bookings)
  else
   render 'new'
  end
  end

def edit

end

def show

end

def update

  if @bookings.update(bookings_params)
    flash[:success] = "Booking Updated"
    redirect_to booking_path(@bookings)
  else
    render 'edit'
  end
  end



private

def bookings_params
  params.require(:booking).permit(:Movie,:Description,:Rating,:user_id,:image, category_ids: [])
  end

  def set_booking
    @bookings = Booking.find(params[:id])
  end

  def require_same_user
    if current_user != @bookings.user and !current_user.admin?
      flash[:danger]="You can Only make Changes to our Posts"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin ,only:[:new,:create]
  
  def index
    @category= Category.paginate(page: params[:page],per_page: 5)
  end
  
  def new
    @category=Category.new
  end
  
  def show
    
  end

  def create
    @category=Category.new(category_params)
    if @category.save
        flash[:success]= "Success"
      redirect_to categories_path
    else
      render 'new'
    end
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only Admin Can perform this Action"
      redirect_to categories_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username:params[:session][:username])

    if user && user.authenticate(params[:session][:password])
        session[:user_id]=user.id
        flash[:success]="Welcome Sir...or Mam....okay I don't know just Welcome"
        redirect_to user_path(user.id)
    else
    flash.now[:danger]="I am Saw-Ry Wrong Password"
    render 'new'
    end

  end

  def delete
    session[:user_id]=nil
    flash[:danger] = "Everyone Left Me Now you too, Come Back Later!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user,only:[:edit,:update,:show]
  before_action :require_same_user, only: [:edit,:update,:delete]
  before_action :require_admin ,only:[:destroy]

  #index
  def index
    @users= User.paginate(page: params[:page], per_page:5)
  end

  #New user Object
  def new
  @users=User.new
  end

  #New User Create
  def create
    @users = User.new(users_params)

    if @users.save
      session[:user_id]=@users.id
      flash[:success] = "Welcome, #{@users.username}"
      redirect_to user_path(@users.id)
    else
      render 'new'
    end
  end

  #Edit Object
  def edit

  end

  #Update Action
  def update

    if @users.update(users_params)
      flash[:success] = "User Deatils Updated"
      redirect_to users_path(@users.id)
    else
      render 'edit'
    end
  end

  #show action

  def show

    @users_bookings= @users.bookings.paginate(page: params[:page], per_page:5)
  end

  #Just a Prank
  def joke

  end

  def delete
    @users=User.find(params[:id])
    @users.destroy
    flash[:danger] = "User and Movies Deleted"
    redirect_to users_path
  end

  def time

  end

  private

  def users_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @users = User.find(params[:id])
  end

  def require_same_user
    if current_user != @users and !current_user.admin?
      flash[:danger] = "You can Only Make Changes to Your Account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only Admin Can perform this Action"
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  redirect_to bookings_path if logged_in?
  end

  def about

  end

  def test

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options={size:80})
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   size=options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end

end

app/views/bookings/_movies.html.erb
<% obj.each do |booking| %>
  <div class="col-xs-4 col-xs-offset-4">
    <div class="well well-lg">
      <div class="movie-title">
        <%= link_to booking.Movie, booking_path(booking) %>
      </div>

      <div class="movie-title">
        <%= image_tag booking.image, class: "movie-image" %>
      </div>

      <div class="movie-body">
        <%= truncate(booking.Description, length: 300) %>
        <div class="booking-meta-details">
          <small>Reviewed By: <%=booking.user.username if booking.user %>
            &nbsp| Created On: <%=time_ago_in_words(booking.created_at)  %>
            &nbsp| Last Updated On: <%= time_ago_in_words(booking.updated_at) %>
          </small>
        </div>
      </div>
      <% if logged_in? && (current_user == booking.user || current_user.admin?) %>
      <div class="movie-actions">
        <%=link_to 'Edit', edit_booking_path(booking), class: "btn btn-xs btn-primary" %>

        <%=link_to 'Delete', delete_booking_path(booking), data:{confirm: "Are you Sure?"},class: "btn btn-xs btn-danger" %>
      </div>
        <%end %>
    </div>
  </div>

<%end %>

app/views/bookings/edit.html.erb
<div class="main-head">
  <h1>Edit Movie</h1>
</div>
<br><br>

<%= render 'layouts/errors', obj: @bookings %>

<%= render 'layouts/form', action:"update" %>

app/views/bookings/index.html.erb
<h1 class="main-head">Movies</h1>
<br><br><br>
<head>
  <style>
table, th, td {
border: 0.5px solid black;
  border-collapse: collapse;
}
  </style>
</head>

<div class="center">
  <%= will_paginate %>
</div>
<%= render 'movies',  obj:@bookings %>
<div class="center">
  <%= will_paginate %>
</div>

app/views/bookings/new.html.erb
<div class="main-head">
<h1>Add Movie</h1>
</div>
<br><br>

<%= render 'layouts/errors', obj: @bookings %>

<%= render 'layouts/form', action:"create" %>

app/views/bookings/show.html.erb
<h2 style="text-align: center"><%= @bookings.Movie %></h2>
<div class="well col-xs-8 col-xs-offset-2">

  <div align="center">
  <div class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li>Added by:</li>
        <li><%= link_to gravatar_for(@bookings.user), user_path(@bookings.user) %></li>
        <li class="booking-title">
          <%= link_to @bookings.user.username, user_path(@bookings.user) %>
        </li>
        <li><small><%= pluralize(@bookings.user.bookings.count, "Movies Added") if @bookings.user.bookings %></small></li>
      </div>
    </div>
  </div>
  </div>

  <h4 class="center description">
    <strong>Description</strong>
    <hr>
      <%=simple_format(@bookings.Description) %>
    <div class="movie-actions">
      <%=link_to 'Back To List', bookings_path,class: "btn btn-xs btn-success" %>
      <%if logged_in? and (current_user == @bookings.user or current_user.admin?) %>
      <%=link_to 'Edit', edit_booking_path(@bookings), class: "btn btn-xs btn-primary" %>
      <%=link_to 'Delete', delete_booking_path(@bookings), data:{confirm: "Are you Sure?"},class: "btn btn-xs btn-danger" %>
      <%end %>
    </div>
  </h4>
</div>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>


<div class="center">
  <%= will_paginate @category %>
</div>


<div align="center">

  <% @category.each do |category| %>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <div class="movie-title">
          <%= link_to "#{category.name}", category_path(category) %>
        </div>
      </div>
    </div>
  <%end %>
</div>

app/views/categories/new.html.erb
<div class="main-head">
  <h1>Add Movie</h1>
</div>
<br><br>

<%= render 'layouts/errors', obj: @category  %>

<%= form_for @category, url:{action:'create'}  do |b| %>
  <div class="form-horizontal">


    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label 'Category Name' %>
      </div>
      <div class="col-sm-10">
        <%= b.text_field :name, class:"form-control", placeholder:"Comedy", autofocus: true %>
      </div>
    </div>




    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= b.submit "Add Category" ,class:"btn btn-primary"%>
      </div>
    </div>
  </div>
<%end %>


<div class="col-xs-4 col-xs-offset-4">
  [ <%=link_to 'Cancel And Back to List', bookings_path %> ]
</div>

app/views/layouts/_dropdown.html.erb
<button class="dropbtn">Categories</button>
<div class="dropdown-content">
  <% if logged_in? %>
    <%if current_user.admin? %>
      <li><%= link_to "Add New Category", new_category_path,class: 'glyphicon glyphicon-plus'%></li>
    <%end %>
  <% end %>

  <!-- All Categories-->

  <li><%= link_to "All Categories", categories_path%>
  </li>

  <% Category.all.each do |cat| %>
    <%= link_to "#{cat.name}", category_path(cat)%>
  <% end %>


  <!-- End -->
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <%end %>
        </ul>
      </div>
    </div>
  </div>
<%end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy;  : <a href="https://www.instagram.com/i_am_alfaaz">Alfaaz Khan</a>
    </small>
  <nav>
    <ul>
      <li><%= link_to 'HomePage', root_path%></li><br>
    <li><%= link_to 'About Us', about_path%></li>
    </ul>
  </nav>
  </footer>
</div>

app/views/layouts/_form.html.erb
<%= form_for @bookings, url:{action: action}  do |b| %>
  <div class="form-horizontal">


    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :Movie %>
      </div>
      <div class="col-sm-10">
        <%= b.text_field :Movie, class:"form-control", placeholder:"Aquaman", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :Poster %>
      </div>
      <div class="col-sm-10">
        <%= b.file_field :image, class:"form-control" %>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :"Your Rating" %>
      </div>
      &nbsp&nbsp&nbsp
      <%= b.select :Rating, [0,1,2,3,4,5,6,7,8,9,10],class:"form-control col-sm-10",default:7%>
    </div>

    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :'Tell Us your Experience!' %>
      </div>
      <div class="col-sm-10">
        <%= b.text_area :Description, class:"form-control" ,rows:10, placeholder:"The Movie Was Enjoyable." %>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= b.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= b.submit "Add Rating" ,class:"btn btn-primary"%>
      </div>
    </div>
  </div>
<%end %>


<div class="col-xs-4 col-xs-offset-4">
  [ <%=link_to 'Cancel And Back to List', bookings_path %> ]
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Bulla Ratings", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Movies", bookings_path,id:"link"%></li>
        <li><%= link_to "Users", users_path,id:"link"%></li>

        <!-- Categories Drop Down -->
        <div class="dropdown">
          <%= render 'layouts/dropdown' %>
        </div>
        <!-- End -->

        <%if logged_in? %>
            <div class="dropdown">
              <button class="dropbtn">Actions</button>
              <div class="dropdown-content">
                <li><%= link_to "Add New Rating", new_booking_path%></li>
                <li><%= link_to "My Ratings", user_path(current_user)%></li>
                <a href="https://www.facebook.com/alfaz.khan.1276">Facebook</a>
                <a href="https://www.instagram.com/i_am_alfaaz">Instagram</a>
              </div>
            </div>

        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-center">
        <%if logged_in?%>
          <%if current_user.admin?%>
            <div style="margin: 10px;margin-left: 7em;">
              <div>
                <div class="btn btn-success btn-sm">Admin</div>
              </div>
            </div>
          <%end %>
        <%end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%if logged_in?%>
            <li><%= link_to "Logout Bye!", bye_path,id:"link"%></li>
                <div class="dropdown">
                  <button class="dropbtn">Your Profile </button>
                  <div class="dropdown-content">
                    <li><%= link_to "Edit Your Profile", edit_user_path(current_user)%></li>
                    <li><%= link_to "Show My Profile", user_path(current_user)%></li>

                    <a href="https://www.facebook.com/alfaz.khan.1276">Facebook</a>
                    <a href="https://www.instagram.com/i_am_alfaaz">Instagram</a>
                  </div>
                </div>
          <% else %>
             <li> <%= link_to "SignUp", signup_path,id:"link" %></li>
              <li><%= link_to "Login", get_in_path,id:"link"%></li>
        <%end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_time_portion.html.erb
<%=Time.now.in_time_zone("Central Time (US & Canada)").to_s.split(" ").second %>

app/views/layouts/_user-errors.html.erb
<% if @user.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@user.errors.count, "Error") %>
            Prevented Movie To Reach Us :-
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <%end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'test' %>

  </head>

  <body>
  <%= render 'layouts/navigation' %>


  <%= render 'layouts/messages' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @users, url:{action: action}  do |b| %>
  <div class="form-horizontal">


    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :UserName %>
      </div>
      <div class="col-sm-10">
        <%= b.text_field :username, class:"form-control", placeholder:"Jake Peralta", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :Email %>
      </div>
      <div class="col-sm-10">
        <%= b.email_field :email, class:"form-control" , placeholder:"example@example.com" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= b.label :Password %>
      </div>
      <div class="col-sm-10">
        <%= b.password_field :password, class:"form-control" , placeholder:"********" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= b.submit(@users.new_record? ? "Sign Up" : "Update", class:"btn btn-primary")%>
      </div>
    </div>
  </div>
<%end %>


<div class="col-xs-4 col-xs-offset-4">
  [ <%=link_to 'Cancel And Back to List', bookings_path %> ]
</div>

app/views/users/edit.html.erb
<h1 class="main-head">Update Details</h1>
<br><br>

<%= render 'layouts/errors', obj: @users %>

<%= render 'form', action: "update" %>

app/views/users/index.html.erb
<h1 class="main-head">All Users</h1>
<br><br>

<div class="center">
  <%= will_paginate %>
</div>

<div align="center">
<% @users.each do |user| %>
  <div class="listing">
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <li><%= link_to gravatar_for(user), user_path(user) %></li>
      <li class="booking-title">
        <%= link_to user.username, user_path(user) %>
      </li>
      <li><small><%= pluralize(user.bookings.count, "Movies Added") if user.bookings %></small></li>
      <%if logged_in? and current_user.admin? %>
      <li><%= link_to "Delete User", delete_user_path(user),class: "btn btn-xs btn-danger" %></li>
        <%end %>
    </div>
  </div>
  </div>
<%end%>
</div>

<div class="center">
  <%= will_paginate %>
</div>

app/views/users/joke.html.erb
<h1 class="main-head">Well Well Well Look Who is in a Hurry!!!</h1>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-prank">
      <div class="panel-heading">
        <ul>
          <p>I gave Creditials to All of my Loved ones. &#10084;</p>
          <p>If you dont't Have Yours then That means</p>
          <ul>
            <li>I don't Love You</li>
            <li>I don't Like You</li>
          </ul>
          <p></p>
          <p>Okay Okay Okay If You are still Insisting me then Just Contact me.</p>
          <p></p>
          <p>You know where to find me Right?</p>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="main-head">SignUp</h1>
<br><br>

<%= render 'layouts/errors', obj: @users %>

<%= render 'form', action: "create" %>

app/views/users/show.html.erb
<h1 class="main-head"><%=@users.username%>'s Page</h1>
<br><br>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @users,size:200 %>
  </div>
</div>

<h4 align="center"><%= @users.username %> Movies</h4>

<div class="center">
  <%= will_paginate @users_bookings %>
</div>
<%= render 'bookings/movies', obj:@users_bookings %>
<div class="center">
  <%= will_paginate @users_bookings%>
</div>

app/views/welcome/about.html.erb
<!doctype html>
<html>
<head>

  <meta charset="utf-8">
  <title>About US</title>
</head>

<body>
<div class="main-head">
  <h4 class="center">
    <strong>About Us</strong>
  </h4>
</div>

<div>
  <div class="well col-xs-8 col-xs-offset-2">
    Hii Guys i am Alfaaz Khan, Computer Science Engineer and a Ruby Lover.
    This Web-App is developed using "Ruby On Rails".
    Ruby ob Rails is a Web Framework of Ruby Language and it is used to
    develop dynamic Websites.

    Its my 2019 Resolution to learn Ruby and along with that I have some more:
    <ul>
      <li>To get Rid of Double Chin</li>
      <li>To Learn One musical Instrument</li>
      <li>To get a Rails Client Project</li>
    </ul>
  </div>
</div>

</body>
</html>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>Bulla Rating</h1>
  <br><br>

  <% if !logged_in? %>

  <%= link_to "I Wanna Join You!", signup_path , class: "btn btn-lg btn-prop" %>
    <%= link_to "Aye! Let Me In", get_in_path, class: "btn btn-lg btn-prop" %>
  <% end %>
</div>

app/views/welcome/test.html.erb
<div class="btn-group dropright ml-2 mt-5">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropright
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>
<div class="btn-group dropleft mt-5 float-right" style="width: 200px;">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-flip="false" aria-haspopup="true" aria-expanded="false">
    Dropleft
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>



<div class="dropdown">
  <button class="dropbtn">Actions</button>
  <div class="dropdown-content">
    <a href="https://www.facebook.com/alfaz.khan.1276">Facebook</a>
    <a href="https://www.instagram.com/i_am_alfaaz">Instagram</a>

    <div class="btn-group dropright ml-2 mt-5">
      <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropright
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>
    <div class="btn-group dropleft mt-5 float-right" style="width: 200px;">
      <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-flip="false" aria-haspopup="true" aria-expanded="false">
        Dropleft
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </div>

  </div>
</div>